sprout: Shim yet another missing symbol
P: GraphicBuffer::lock(uint32_t inUsage, void** vaddr);
Q: GraphicBuffer::lock(uint32_t inUsage, void** vaddr, int32_t* outBytesPerPixel, int32_t* outBytesPerStride);
Error: cannot locate symbol "_ZN7android13GraphicBuffer4lockEjPPv" referenced by "/system/lib/libcam_utils.so".

Signed-off-by: SamarV-121 <samarvispute121@gmail.com>